main – greeting
main Program
26 statements
Source File
Uses
greeting
モジュールgreetingで定義されている手続をテストする．
テストには
宛名を指定して歓迎のメッセージを作成する手続 create_greeting_message_to に対するテスト
が含まれる．
Calls
Contents
Variables
actual expected name
Interfaces
assert
Subroutines
assert_str_str
Variables
Type Attributes Name Initial
character, allocatable :: actual
character, parameter :: expected = "Hello "//name//" !"
character, parameter :: name = "GitHub Actions"
Interfaces
interface assert
subroutine assert_str_str(actual, expected)
二つの文字列actual, expectedが等しいかを検査する． 等しくない場合は，それぞれの内容を表示してerror stopする．
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: actual
character, intent(in) :: expected
Subroutines
subroutine assert_str_str(actual, expected)
二つの文字列actual, expectedが等しいかを検査する． 等しくない場合は，それぞれの内容を表示してerror stopする．
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: actual
character, intent(in) :: expected
Call graph
main calls create_greeting_message_to, assert
assert calls assert_str_str